### ISSUE TITLE
Some notes.

### ISSUE THREAD

**Issue by oshogbo** [yuichiro-naito/asmctl#10]
https://github.com/yuichiro-naito/asmctl/blob/659f1e3b7f4d71820320d08805095a6eef7f1248/src/asmctl.c#L386

cap_enter can fail and you should check that.
After creating services you can close casper services.
You can limit the system.sysctl only to few sysctls you really need.

Thanks for working on that :)

**Comment by yuichiro-naito** [comment]
Thanks for reviewing my code.

> cap_enter can fail and you should check that.

I read the manual of cap_enter(2).
If the kernel is not supported capsicum, cap_enter fails.
I changed the code to check this.

> After creating services you can close casper services.

Yes, this is mentioned in your sides of BSDtw.
I fixed my code.

> You can limit the system.sysctl only to few sysctls you really need.

Do you mean about cap_service_limit() function ?
I couldn't find the function in manuals.
I will check the behavior later.

**Comment by yuichiro-naito** [comment]
I understand cap_limit_set() limits which sysctl name is allowed to read / write.

The Pull Request #11 fixes all issues @oshogbo mentioned.
Thanks for reviewing my code!
