### ISSUE TITLE
cap_service_limit failed Invalid argument

### ISSUE THREAD

**Issue by nightstalkerns** [yuichiro-naito/asmctl#14]
Hello,
On FreeBSD 13.0-RELEASE, invoking asmctl always outputs "cap_service_limit failed Invalid argument". On previous FreeBSD versions, asmctl worked as expected.

**Comment by yuichiro-naito** [comment]
Thanks for reporting.
I'm going to fix this problem.

**Comment by nightstalkerns** [comment]
Hello,

Le Fri, 21 May 2021 08:57:06 -0700,
Yuichiro Naito ***@***.***> a écrit :

> Thanks for reporting.
> I'm going to fix this problem.

Great :)
Thanks for the asmctl tool!

-- 
matt [at] lv223.org
GPG key ID: 7D91A8CA

**Comment by nightstalkerns** [comment]
Hello,

Le Fri, 21 May 2021 08:57:06 -0700,
Yuichiro Naito ***@***.***> a écrit :

> Thanks for reporting.
> I'm going to fix this problem.

There's also a typo on asmctl(1) manpage. The kernel driver 'asmctl.ko'
doesn't exist. Wouldn't be instead 'asmc.ko'?

Cheers

-- 
matt [at] lv223.org
GPG key ID: 7D91A8CA

**Comment by yuichiro-naito** [comment]
>There's also a typo on asmctl(1) manpage. The kernel driver 'asmctl.ko'
>doesn't exist. Wouldn't be instead 'asmc.ko'?

Oh, yes. I'll fix this, too.

**Comment by yuichiro-naito** [comment]
Does anybody check the latest version 1.9?
I fixed all bugs reported above messages.

If version 1.9 is OK, I'll make a request of updating sysutils/asmctl port.

**Comment by nightstalkerns** [comment]
Le Sat, 22 May 2021 02:21:20 -0700,
Yuichiro Naito ***@***.***> a écrit :

> Does anybody check the latest version 1.9?
> I fixed all bugs reported above messages.
> 
> If version 1.9 is OK, I'll make a request of updating sysutils/asmctl
> port.
> 

Just tested master branch and it works flawlessly on stock 13.0-RELEASE
(MacbookPro9,2 here)! Thanks :)

Cheers

-- 
matt [at] lv223.org
GPG key ID: 7D91A8CA
